### ISSUE TITLE
Can't get pynq notebooks

### ISSUE THREAD

**Issue by afireswallow** [Xilinx/DPU-PYNQ#103]
I have successfully installed the dpu-pynq by running the command "pip3 install pynq-dpu --no-build-isolation" in my customized zu19eg board. But i can't successfully run the command "pynq get-notebooks pynq-dpu -p .", and I don't know whether this is successful or not when I run the command "python3 -m pytest --pyargs pynq_dpu". 

root@pynq:/home/xilinx/jupyter_notebooks# pynq get-notebooks pynq-dpu -p . --force
Delivering notebooks './pynq-dpu'...
The notebooks module 'pynq-dpu' could not be delivered. The module has no notebooks, or no valid overlays were found
root@pynq:/home/xilinx/jupyter_notebooks# python3 -m pytest --pyargs pynq_dpu
==================================================== test session starts =====================================================
platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/xilinx/jupyter_notebooks
plugins: dash-2.10.2, anyio-3.1.0, sourceorder-0.5.1
collected 0 items

================================================ no tests ran in 0.08 seconds ================================================

Thanks!

**Comment by skalade** [comment]
Hi @afireswallow,

It looks like your notebooks didn't get delivered either, something must've got wrong in the installation... Could you confirm your BOARD variable contents?

In terminal just run:
`echo $BOARD`

The .link files assume that for your board the BOARD variable would be [TySOM-3A-ZU19EG](https://github.com/Xilinx/DPU-PYNQ/blob/master/pynq_dpu/dpu.bit.link#L46) , but perhaps that is wrong.

If the BOARD variable doesn't match what's in the .link files, an easy workaround would be to uninstall pynq_dpu, manually set your BOARD variable to TySOM-3A-ZU19EG, e.g. `export BOARD=TySOM-3A-ZU19EG`. Then run the pip install again.

Hope that helps.

Thanks
Shawn

**Comment by afireswallow** [comment]
@skalade Thanks for your reply!
I have already try it.

----------------------------------------------------------------------------------------------
root@pynq:~# pip3 install pynq-dpu --no-build-isolation
Processing ./.cache/pip/wheels/f4/3a/e3/29e0c57ad00d304ad212488b6ebae815a8c4d0f39d2dcc5964/pynq_dpu-1.4.0-cp38-cp38-linux_aarch64.whl
Collecting pybind11
  Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
Collecting pynq>=2.7.0
  Using cached pynq-3.0.1.tar.gz (63.0 MB)
Collecting mnist
  Using cached mnist-0.2.2-py2.py3-none-any.whl (3.5 kB)
Processing ./.cache/pip/wheels/7d/f0/ee/af6e3d91d8ef23c0496fb78df6d17e73f037da4fcabf68b273/CppHeaderParser-2.7.4-py3-none-any.whl
Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (1.14.0)
Collecting nest_asyncio
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (1.17.4)
Requirement already satisfied: pynqmetadata>=0.0.1 in /usr/local/lib/python3.8/dist-packages (from pynq>=2.7.0->pynq-dpu) (0.1.5)
Requirement already satisfied: pynqutils>=0.0.1 in /usr/local/lib/python3.8/dist-packages (from pynq>=2.7.0->pynq-dpu) (0.1.1)
Requirement already satisfied: setuptools>=24.2.0 in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (45.2.0)
Requirement already satisfied: ply in /usr/lib/python3/dist-packages (from CppHeaderParser->pynq-dpu) (3.11)
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (from pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (1.10.9)
Requirement already satisfied: jsonschema>=3.2.0 in /usr/local/lib/python3.8/dist-packages (from pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.17.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from pynqutils>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.65.0)
Requirement already satisfied: python-magic>=0.4.25 in /usr/local/lib/python3.8/dist-packages (from pynqutils>=0.0.1->pynq>=2.7.0->pynq-dpu) (0.4.27)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.8/dist-packages (from pydantic->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.6.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (5.12.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (19.3.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages(from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (1.3.10)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (3.15.0)
Building wheels for collected packages: pynq
  Building wheel for pynq (setup.py) ... done
  Created wheel for pynq: filename=pynq-3.0.1-cp38-cp38-linux_aarch64.whl size=11475907 sha256=0c63d066297645bf12b8b8cc224146a2838677c8a980d79adcf17f36c0c8de87
  Stored in directory: /root/.cache/pip/wheels/74/b5/c5/ba33b53129fe9ede10c2aaf4484be7b622edffde1831583e36
Successfully built pynq
Installing collected packages: pybind11, nest-asyncio, pynq, mnist, CppHeaderParser, pynq-dpu
Successfully installed CppHeaderParser-2.7.4 mnist-0.2.2 nest-asyncio-1.5.6 pybind11-2.10.4 pynq-3.0.1 pynq-dpu-1.4.0
root@pynq:~# cd $PYNQ_JUPYTER_NOTEBOOKS
root@pynq:/home/xilinx/jupyter_notebooks# pynq get-notebooks pynq-dpu -p . --force
/usr/local/lib/python3.8/dist-packages/pynq/pl_server/device.py:56: UserWarning: No devices found, is the XRT environment sourced?
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/pynq-get-notebooks", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pynq/_cli/get_notebooks.py", line 155, in main
    device = _detect_devices(active_only=True)
  File "/usr/local/lib/python3.8/dist-packages/pynq/utils.py", line 53, in _detect_devices
    raise RuntimeError("No device found in the system")
RuntimeError: No device found in the system
--------------------------------------------------------------------------------------------------

As I restarted the machine afterwards, the prompt changed

--------------------------------------------------------------------------------------------------
root@pynq:/# export BOARD=TySOM-3A-ZU19EG
root@pynq:/# pip
bash: pip: command not found
root@pynq:/# pip3 install pynq-dpu
Requirement already satisfied: pynq-dpu in /usr/local/lib/python3.8/dist-packages (1.4.0)
Requirement already satisfied: pynq>=2.7.0 in /usr/lib/python3.8/site-packages (from pynq-dpu) (3.0.1)
Requirement already satisfied: mnist in /usr/lib/python3.8/site-packages (from pynq-dpu) (0.2.2)
Requirement already satisfied: CppHeaderParser in /usr/lib/python3.8/site-packages (from pynq-dpu) (2.7.4)
Requirement already satisfied: pybind11 in /usr/lib/python3.8/site-packages (from pynq-dpu) (2.10.4)
Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (1.14.0)
Requirement already satisfied: nest_asyncio in /usr/lib/python3.8/site-packages (from pynq>=2.7.0->pynq-dpu) (1.5.6)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (1.17.4)
Requirement already satisfied: pynqmetadata>=0.0.1 in /usr/lib/python3.8/site-packages (from pynq>=2.7.0->pynq-dpu) (0.1.5)
Requirement already satisfied: pynqutils>=0.0.1 in /usr/lib/python3.8/site-packages (from pynq>=2.7.0->pynq-dpu) (0.1.1)
Requirement already satisfied: setuptools>=24.2.0 in /usr/lib/python3/dist-packages (from pynq>=2.7.0->pynq-dpu) (45.2.0)
Requirement already satisfied: ply in /usr/lib/python3/dist-packages (from CppHeaderParser->pynq-dpu) (3.11)
Requirement already satisfied: jsonschema>=3.2.0 in /usr/lib/python3.8/site-packages (from pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.17.3)
Requirement already satisfied: pydantic in /usr/lib/python3.8/site-packages (from pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu)(1.10.9)
Requirement already satisfied: python-magic>=0.4.25 in /usr/lib/python3.8/site-packages (from pynqutils>=0.0.1->pynq>=2.7.0->pynq-dpu) (0.4.27)
Requirement already satisfied: tqdm in /usr/lib/python3.8/site-packages (from pynqutils>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.65.0)
Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in /usr/lib/python3.8/site-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (5.12.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/lib/python3.8/site-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (19.3.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10; python_version < "3.9" in /usr/lib/python3.8/site-packages (fromjsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (1.3.10)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/lib/python3.8/site-packages (from pydantic->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (4.6.3)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/lib/python3.8/site-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema>=3.2.0->pynqmetadata>=0.0.1->pynq>=2.7.0->pynq-dpu) (3.15.0)
root@pynq:/# cd $PYNQ_JUPYTER_NOTEBOOKS
root@pynq:/home/xilinx/jupyter_notebooks# pynq get-notebooks pynq-dpu -p . --force
/usr/lib/python3.8/site-packages/pynq/pl_server/xrt_device.py:59: UserWarning: xbutil failed to run - unable to determine XRTversion
  warnings.warn("xbutil failed to run - unable to determine XRT version")
/usr/lib/python3.8/site-packages/pynq/pl_server/xrt_device.py:59: UserWarning: xbutil failed to run - unable to determine XRTversion
  warnings.warn("xbutil failed to run - unable to determine XRT version")
Delivering notebooks './pynq-dpu'...
The notebooks module 'pynq-dpu' could not be delivered. The module has no notebooks, or no valid overlays were found
--------------------------------------------------------------------------------------------------


How can I do?

Thanks

**Comment by afireswallow** [comment]
more information about my xrt:
```
root@pynq:/# xbutil list
INFO: Found total 1 card(s), 1 are usable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:        Linux
Release:        5.4.0-xilinx-v2020.2
Version:        #1 SMP Fri May 19 02:40:23 UTC 2023
Machine:        aarch64
Glibc:          2.31
Distribution:   PynqLinux, based on Ubuntu 20.04
Now:            Wed Jun 21 07:03:11 2023 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:        2.8.0
Git Hash:       7c93966ead2dec777b92bdc379893f22b5bd561e
Git Branch:     temp
Build Date:     2023-05-19 09:54:56
ZOCL:           2.8.0,7c93966ead2dec777b92bdc379893f22b5bd561e
 [0]:ZU19EG
root@pynq:/# xbutil --version
ERROR: Unknown comand '--version'
Running xbutil for 4.0+ shell's

Usage: xbutil <command> [options]

Command and option summary:
  clock   [-r region] [-f clock1_freq_MHz] [-g clock2_freq_MHz] [-h clock3_freq_MHz]
  dmatest [-b [0x]block_size_KB]
  dump
  help
  m2mtest
  mem --read [-a [0x]start_addr] [-i size_bytes] [-o output filename]
  mem --write [-a [0x]start_addr] [-i size_bytes] [-e pattern_byte]
  program [-r region] -p xclbin
  query   [-r region]
  status [--debug_ip_name]
  scan
  top [-i seconds]
  validate

Examples:
Print JSON file to stdout
  xbutil dump
List all cards
  xbutil list
Scan for Xilinx EDGE card(s) & associated drivers (if any) and relevant system information
  xbutil scan
Change the clock frequency of region 0 to 100 MHz
  xbutil clock -f 100
For card 0 which supports multiple clocks, change the to 200MHz and clock 2 to 250MHz
  xbutil clock -f 200 -g 250
Download the accelerator program on card
  xbutil program -p a.xclbin
Run DMA test with 32 KB blocks of buffer
  xbutil dmatest -b 0x20
Read 256 bytes from DDR starting at 0x1000 into file read.out
  xbutil mem --read -a 0x1000 -i 256 -o read.out
  Default values for address is 0x0, size is DDR size and file is memread.out
Write 256 bytes to DDR starting at 0x1000 with byte 0xaa
  xbutil mem --write -a 0x1000 -i 256 -e 0xaa
  Default values for address is 0x0, size is DDR size and pattern is 0x0
List the debug IPs available on the platform
  xbutil status
Validate installation on card
  xbutil validate
```
When I try to reinstall xrt, pynqlinux doesn't seem to be supported
```
root@pynq:/# ./XRT/src/runtime_src/tools/scripts/xrtdeps.sh
unknown OS flavor pynqlinux
```
How can I proceed?

**Comment by afireswallow** [comment]
it's not necessary for above command. It runs successfully in my board without dealing with above questions
