### ISSUE TITLE
tf_yolov3_voc model deploy and train on the PYNQ-Z2

### ISSUE THREAD

**Issue by B1D1ng** [Xilinx/DPU-PYNQ#11]
Hello, if I want to use the tf_yolov3_voc model in the Vitis AI Model Zoo to deploy and train on the PYNQ-Z2 board, should I follow this tutorial step by step, right? Does train_mnist_model.ipynb apply to my own custom dataset? For example, if I want to train the tf_yolov3_voc and detect the smoke on PYNQ-Z2.

**Comment by yunqu** [comment]
Z2 support in VAI 1.3

**Comment by Sellto** [comment]
Hi, I'm Really interrested to use the DPU on the pynq-z2 too
