### ISSUE TITLE
When will PYNQ-Z2 be supported?

### ISSUE THREAD

**Issue by Stealers** [Xilinx/DPU-PYNQ#14]
When will PYNQ-Z2 be supported? Thanks.

**Comment by yunqu** [comment]
In VAI 1.3

**Comment by Wo-Ki** [comment]
I can't wait to try it on pynq-z2.

**Comment by Wo-Ki** [comment]
> In VAI 1.3

Hi, Vitis AI is v1.3 now, but I I don't see any update for pynq-z2, is there any thing wrong?

**Comment by Sellto** [comment]
Hi, I'm Really interrested to use the DPU on the pynq-z2 too
