### ISSUE TITLE
Ultra96 dcf file ?

### ISSUE THREAD

**Issue by gjkunde** [Xilinx/DPU-PYNQ#26]
Hello,

the ULTRA96 json file references:

    "target"   : "DPUCZDX8G",
    "dcf"      : "/opt/vitis_ai/compiler/arch/DPUCZDX8G/Ultra96/Ultra96.dcf",
    "cpu_arch" : "arm64"

alas Vitis 1.2 does not have an ULTRA96 directory in /opt/vitis_ai/compiler/arch/DPUCZDX8G/
it appears necessary to not only post the pynqdpu.dpu.ultra96.hwh file but the dcf as well ?

Thank you for your support, Gerd

**Comment by yunqu** [comment]
It should be generated when running the script: https://github.com/Xilinx/DPU-PYNQ/blob/master/host/compile.sh#L37

**Comment by gjkunde** [comment]
Thank you for the quick response, I am on the quest to run 

https://github.com/Xilinx/DPU-PYNQ/blob/master/host/train_mnist_model.ipynb, so I did not use the 
compile.sh script for that seems to be designed for the model zoo zip file.

I see the "dlet -f" command there, just did not expect them in the compile script :-)

**Comment by balintmaci** [comment]
I recommend that you run compile.sh before running the notebook just so it copies the required files, that's the quickest way
