### ISSUE TITLE
overlay.load_model(<resnet50>_<ultra96>.xmodel) makes kernel die.

### ISSUE THREAD

**Issue by JianmingTONG** [Xilinx/DPU-PYNQ#47]
Hi I have followed the readme.md of DPU-PYNQ  
Here are my status. I used PYNQ2.6 image for Ultra96v2.
1. [step 1 -- succeed] After successfully finishing step 1 of the readme.md of DPU-PYNQ to upgrade the DPU-PYNQ for PYNQ2.6
2. [step 2 -- succeed] And I use wget to download the released  .bit, .hwh, .xclbin, and .xmodel files for ultra96.
3. [step 3 -- kernel died in model_load] When I open the dpu_resnet50.ipynb in jupyter_note and change the .xmodel and .bit files into correct name. And click on run button. The kernel died. Might I ask how to fix that?

Here is the overlay info
```
IP Blocks
----------
axi_vip_2            : pynq.overlay.DefaultIP
DPUCZDX8G_1          : pynq.overlay.DefaultIP
axi_vip_1            : pynq.overlay.DefaultIP
ps_e_0               : pynq.overlay.DefaultIP
```

Here are the files that I used.
1. .model 
```
"Ultra96": {
        "url": "https://www.xilinx.com/bin/public/openDownload?filename=pynqdpu.dpu_resnet50.ultra96.1.3.0.xmodel",
        "md5sum": "489ed4dc13e755d82e3a4cf87bf6866e"
    },
```
2. dpu.bit
```
"Ultra96": {
        "url": "https://www.xilinx.com/bin/public/openDownload?filename=pynqdpu.dpu.ultra96.1.3.0.bit",
        "md5sum": "20f59c652cab14cbf75d308be7f2dd79"
    }
```
3. dpu.hwh
```
"Ultra96": {
        "url": "https://www.xilinx.com/bin/public/openDownload?filename=pynqdpu.dpu.ultra96.1.3.0.hwh",
        "md5sum": "5e680bb06d92450d44701ec355e68136"
    }
```
4. dpu.xclbin
```
	"Ultra96": {
        "url": "https://www.xilinx.com/bin/public/openDownload?filename=pynqdpu.dpu.ultra96.1.3.0.xclbin",
        "md5sum": "c1c9069ab68b7826b77538407e72061f"
    },
```

Any instruction is appreciated!
Thanks in advance!
JT

**Comment by yunqu** [comment]
Please use our suggested Vitis-AI docker version to rebuild your xmodel file.
