### ISSUE TITLE
Problem importing VART

### ISSUE THREAD

**Issue by majlucaaa** [Xilinx/DPU-PYNQ#50]
Hi, I am using Pynq in the ZCU104 board and have a problem when I try to import the vart module, when I write "import vart" this error appears
"ModuleNotFoundError: No module named 'vart'". What should I do?

**Comment by schelleg** [comment]
Yes, youhave to append `usr/lib/python3.6/site-packages` to sys.path to pick up the vart python bindings.  See the code below:

https://github.com/Xilinx/DPU-PYNQ/blob/master/pynq_dpu/dpu.py#L17
