### ISSUE TITLE
How to use multiple threads to improve performance? 

### ISSUE THREAD

**Issue by daivikbhatia** [Xilinx/DPU-PYNQ#52]
The dpu_resnet50.ipynb file inside board image says this line:
"We can also run it for multiple images as shown below. In this example we have only used 1 thread; in principle, users should be able to boost the performance by employing more threads."

How can I achieve this to get FPS around 30?

**Comment by schelleg** [comment]
I'd recommend you look over the Vitis AI documentation for optimization techniques...
https://www.xilinx.com/html_docs/vitis_ai/1_3/running_examples.html#ariaid-title2
