### ISSUE TITLE
DPU on PYNQ-Z1/2

### ISSUE THREAD

**Issue by AbdouTobblaze** [Xilinx/DPU-PYNQ#55]
Hi, I'm very interrested on using DPU on the PYNQ-Z2 plateform and according to xilinx the DPU v3.3 is supported on zynq-7000 series (https://www.xilinx.com/html_docs/vitis_ai/1_3/dpu_intro.html#gub1565042860537). Can anyone tell me how to modify the sources to get it working with this board ?

**Comment by schelleg** [comment]
refer to https://github.com/Xilinx/DPU-PYNQ/issues/22
