### ISSUE TITLE
Pynq-DPU install takes a lot of time

### ISSUE THREAD

**Issue by zackdilan** [Xilinx/DPU-PYNQ#6]
I am facing a lot of time delay in installing pynq dpu . Is it normal or not? I was able to successfully build the pynq upgrade. Please let me know.

**Comment by yunqu** [comment]
Which step are you referring to exactly? How much time does it take?

**Comment by zackdilan** [comment]
the pip install pynq-dpu step. 
![out](https://user-images.githubusercontent.com/50382476/84051298-38784b00-a9af-11ea-99b8-0b937d37151e.PNG)

**Comment by yunqu** [comment]
Is this based on pynq 2.5 image and you have run our upgrade? It looks like you do not have proper pynq package installed.

**Comment by zackdilan** [comment]
Yes this is based on pynq 2.5 image and done the pynq image upgrade successfully.

**Comment by yunqu** [comment]
We have tested the whole flow based on a clean 2.5 image. I did not see this issue; so maybe you changed something on the image?

**Comment by zackdilan** [comment]
Yes, there were some problems with my image, I tried to do the whole process again and it worked. Thanks
