### ISSUE TITLE
Subgraphs on CPU

### ISSUE THREAD

**Issue by luke-avionics** [Xilinx/DPU-PYNQ#60]
I managed to run multiple subgraphs on DPU by changing the dpu.py code. However, is there anyway to run the subgraphs on CPU?

**Comment by skalade** [comment]
This looks related to https://github.com/Xilinx/DPU-PYNQ/issues/72. At the moment we don't have strong subgraph support, which is highly dependent on the Vitis AI API and availability of Python examples.
