### ISSUE TITLE
pynq-dpu 1.2.0

### ISSUE THREAD

**Issue by XiongDa0001** [Xilinx/DPU-PYNQ#61]
Hi, how can i get the wheel of dpu-pynq 1.2.0?

**Comment by skalade** [comment]
This is an old issue, so hopefully solved by now. But for future reference you could checkout the v1.2 tag and build it like in [this stackoverflow answer](https://stackoverflow.com/questions/26059111/build-a-wheel-egg-and-all-dependencies-for-a-python-project).
