### ISSUE TITLE
Is DPU-PYNQ compatible with custom accelerator?

### ISSUE THREAD

**Issue by aclich** [Xilinx/DPU-PYNQ#66]
The DPU-PYNQ uses DpuOverlay for loading the DPU bitstream and I would like to know that is the bitstream containing DPU and other accelerator (custom HLS IP) still working? Can the custom accelerator running with the same code in PYNQ?
Thanks for your hard work!

**Comment by schelleg** [comment]
Yes, that should work though I don't know if we've tested (or seen) a custom DPU instance or custom bitstream running withthe DpuOverlay class.  Maybe others have examples
