### ISSUE TITLE
DPU-PYNQ for PYNQ-Z2 Board

### ISSUE THREAD

**Issue by RanyaJumah** [Xilinx/DPU-PYNQ#67]
Hello,

will Visit AI support PYNQ-Z2 Board? thanks.

**Comment by schelleg** [comment]
DPU-PYNQ only supports Zynq UltraScale+ parts right now.  

For all general Vitis-AI questions, we recommend people ask on the [Vitis-AI GitHub.](https://github.com/Xilinx/Vitis-AI)

**Comment by schelleg** [comment]
please reopen if more discussion...
