### ISSUE TITLE
About model format

### ISSUE THREAD

**Issue by NoLookDefense** [Xilinx/DPU-PYNQ#74]
Hello. I am not clear about the model format.
In the "host" folder, the target is to convert the model into .xmodel file. However, in the "pynq_dpu" folder, the examples use ".elf" model as the input.
I wonder what's the relationship between them, and how to convert?

**Comment by skalade** [comment]
Hi there,

The ".elf" file format was supported in previous iterations of VART and DNNDK (which is now deprecated), starting from Vitis AI v1.3.0 the default format is ".xmodel", which is what DPU-PYNQ supports.

Thanks
Shawn
