### ISSUE TITLE
Vitis AI 2.0

### ISSUE THREAD

**Issue by rpitonak** [Xilinx/DPU-PYNQ#78]
Hello,

Are there any plans to support models compiled by Vitis AI 2.0 Compiler?

Thank you!

**Comment by skalade** [comment]
Hi there, that is certainly the intention for the next release. Can't give an estimate on when that will be right now though.

Thanks

**Comment by rpitonak** [comment]
Thank you for your prompt reply. 

Closing the issue now and looking forward to the next release.
