### ISSUE TITLE
Use Vivado to build the Hardware 

### ISSUE THREAD

**Issue by HenningCode** [Xilinx/DPU-PYNQ#81]
Hello,

I want to create a custom hardware design because I need some GPIO. I wanted to create the design with this [tutorial](https://github.com/Xilinx/Vitis-AI/blob/master/dsa/DPU-TRD/prj/Vivado/README.md) and was wondering if I can just build the hardware like that and use it for pynq ?

Greetings

**Comment by skalade** [comment]
Hi there,

Yes, there is no reason you shouldn't be able to use your own hardware design, as long as it has the DPU IP in it. You would just have to copy your new dpu.bit, dpu.hwh and dpu.xclbin files into the pynq_dpu installation.

I'll close this out as it's not really an issue with DPU-PYNQ, but if you have any questions like this I recommend making a post on the [pynq support forum](https://discuss.pynq.io/).

Thanks
Shawn
