### ISSUE TITLE
Will the latest DPU-PYNQ support Vitis-AI 2.5 and DPU v4.0?

### ISSUE THREAD

**Issue by anirudhitagi** [Xilinx/DPU-PYNQ#89]
Greetings,

I plan to use an ultra96v2 board and deploy [tf_mobilenetv2_1.4_imagenet_224_224_1.16G_2.5](https://github.com/Xilinx/Vitis-AI/tree/master/model_zoo/model-list/tf_mobilenetv2_1.4_imagenet_224_224_1.16G_2.5) on it. I used the latest Vitis-AI (Docker build: 2.5.0.1260) to quantize and compile the tensorflow model into the xmodel. And I did this by using the latest [DPUCZDX8G](https://www.xilinx.com/bin/public/openDownload?filename=DPUCZDX8G.tar.gz) (DPU v4.0).  I also generated bit programming file with the same DPU IP

I plan to program the PL with DpuOverlay with above mentioned bitstream, and then deploy and execute the xmodel with vart/runner. 

But will DPU-PYNQ v 1.4 support what I mentioned above?
or do I have to revert to earlier versions of Vitis-ai and DPU?

Any inputs would be much appreciated.

Thanks & Regards,
-AI

**Comment by skalade** [comment]
Hi there,

There was an issue in the past https://github.com/Xilinx/DPU-PYNQ/issues/77 of newer Vitis AI models not working with the current version of DPU-PYNQ. The safest option is likely to stick with v1.4 for now if you want to use DPU-PYNQ.

Thanks
Shawn

**Comment by anirudhitagi** [comment]
Thank you for the clarification! Much appreciated!
