### ISSUE TITLE
PYNQ + Vitis Library

### ISSUE THREAD

**Issue by zackdilan** [Xilinx/DPU-PYNQ#9]
Hi, I would like to know the possibilities of using Vitis AI library with the DPU-PYNQ package say for Ultra96? Is it possible by any means? Thanks in advance.

**Comment by proelf98** [comment]
Hey @zackdilan yes it is possible to use the Vitis AI library on the Ultra96:
There is an example here: https://github.com/Xilinx/PYNQ-HelloWorld/tree/master/pynq_helloworld/notebooks/edge
